<a href="https://colab.research.google.com/github/sunnatillo91/Task/blob/main/math_in_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chiziqli algebra

In [ ]:
# import numpy library
import numpy as np

## Adding vectors

In [ ]:
A = [4, 8, 7]
B = [5, -4, 9]

# Adding vectors
# C = [A[0] + B[0], A[1] + B[1], A[2] + B[2]]
C = np.add(A, B)
print("Result of adding A vector to B vector", C)
# C

Result of adding A vector to B vector [ 9  4 16]


## Multiplying vectors

In [ ]:
A = [4, 8, 7]
B = [5, -4, 9]

# multiplying A vector to B vector
res = np.multiply(A,B)
res

array([ 20, -32,  63])

## Matritsalar bilan ishlash

In [ ]:
# 2 qator va 2 ustundan iborat matritsa hosil qilamiz

matritsa_1 = np.array([[3, 4], [5, 6]])
matritsa_2 = np.array([[8, 9], [0, 6]])

# .add metodi yordamida mos ustun va qatorlarni qo'shamiz
natija1 = np.add(matritsa_1, matritsa_2)
natija1

array([[11, 13],
       [ 5, 12]])

In [ ]:
# .dot metodi yordamida mos ustun va qatorlarni ko'paytiramiz
res = np.dot(matritsa_1, matritsa_2)

In [ ]:
res

array([[24, 51],
       [40, 81]])